@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Aug 15 14:23:13 +0300 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim mem_stage_tb_behav -key {Behavioral:sim_1:Functional:mem_stage_tb} -tclbatch mem_stage_tb.tcl -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/inst_bram_tb_behav.wcfg -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/fetch_tb_behav.wcfg -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/decode_tb_behav.wcfg -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/execution_tb_behav.wcfg -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/write_back_behav.wcfg -log simulate.log"
call xsim  mem_stage_tb_behav -key {Behavioral:sim_1:Functional:mem_stage_tb} -tclbatch mem_stage_tb.tcl -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/inst_bram_tb_behav.wcfg -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/fetch_tb_behav.wcfg -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/decode_tb_behav.wcfg -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/execution_tb_behav.wcfg -view D:/BarIlan/DDP/exercises/RiscV_pipe/riscv_pipe/riscv_pipe/write_back_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
